<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.bridgelabs.AdressBookTest" tests="1" skipped="0" failures="0" errors="0" timestamp="2021-08-18T02:35:48" hostname="DESKTOP-M71IR21" time="1.504">
  <properties/>
  <testcase name="givenAdressBookInDB_WhenRetrieved_ShouldMatchpersonCount" classname="com.bridgelabs.AdressBookTest" time="1.504"/>
  <system-out><![CDATA[Connecting to database: jdbc:mysql://localhost:3306/adressbook
Connection is successful! com.mysql.cj.jdbc.ConnectionImpl@58b52ad6
Connecting to database: jdbc:mysql://localhost:3306/adressbook
Connection is successful! com.mysql.cj.jdbc.ConnectionImpl@67f0bb44
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
